import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { spawn } from 'child_process';

const JOB_ROOT = process.env.AERMOD_JOB_ROOT || path.join(process.cwd(), 'data', 'aermod-jobs');

export function assessAermodReadiness(manifest = {}) {
  const required = ['controlFile', 'sourceInventory', 'receptorDefinition', 'meteorology', 'terrain', 'buildingDownwash'];
  const missing = required.filter(key => !manifest[key]);
  return {
    ready: missing.length === 0 && !!process.env.AERMOD_EXECUTABLE,
    executableConfigured: !!process.env.AERMOD_EXECUTABLE,
    missing,
    modelVersion: manifest.modelVersion || null,
    officialReference: 'https://www.epa.gov/scram/air-quality-dispersion-modeling-preferred-and-recommended-models',
    reviewGates: ['Agency-approved modeling protocol', 'Qualified modeler QA/QC', 'Background concentration selection', 'Final result interpretation'],
  };
}

export function buildAermodPackage({ project, sources = [], receptors = [], options = {} }) {
  if (!project?.title) throw new Error('AERMOD project title is required');
  if (!sources.length) throw new Error('At least one modeled source is required');
  if (!receptors.length) throw new Error('At least one receptor is required');
  const modelVersion = options.modelVersion || '24142';
  const control = [
    'CO STARTING',
    `   TITLEONE ${sanitize(project.title).slice(0, 68)}`,
    `   TITLETWO Generated by Brick PermitOS; model version target ${modelVersion}`,
    `   MODELOPT ${options.modeOptions || 'CONC FLAT'}`,
    `   AVERTIME ${options.averagingTimes || '1 24 ANNUAL'}`,
    '   POLLUTID GENERIC',
    '   RUNORNOT RUN',
    'CO FINISHED',
    'SO STARTING',
    ...sources.flatMap(source => [
      `   LOCATION ${sanitizeId(source.id)} POINT ${number(source.x)} ${number(source.y)} ${number(source.elevation || 0)}`,
      `   SRCPARAM ${sanitizeId(source.id)} ${number(source.emissionRate)} ${number(source.stackHeight)} ${number(source.exitTemperature)} ${number(source.exitVelocity)} ${number(source.stackDiameter)}`,
    ]),
    'SO FINISHED',
    'RE STARTING',
    ...receptors.map(receptor => `   DISCCART ${number(receptor.x)} ${number(receptor.y)} ${number(receptor.elevation || 0)} ${number(receptor.hillHeight || 0)}`),
    'RE FINISHED',
    'ME STARTING',
    `   SURFFILE ${options.surfaceFile || 'surface.sfc'}`,
    `   PROFFILE ${options.profileFile || 'profile.pfl'}`,
    `   SURFDATA ${options.surfaceStation || '00000'} ${options.dataYear || '2025'}`,
    `   UAIRDATA ${options.upperAirStation || '00000'} ${options.dataYear || '2025'}`,
    'ME FINISHED',
    'OU STARTING',
    '   RECTABLE ALLAVE FIRST',
    '   MAXTABLE ALLAVE 50',
    '   SUMMFILE aermod.sum',
    'OU FINISHED',
  ].join('\n');
  return {
    modelVersion,
    files: {
      'aermod.inp': Buffer.from(control).toString('base64'),
      'manifest.json': Buffer.from(JSON.stringify({ project, sources, receptors, options, modelVersion }, null, 2)).toString('base64'),
    },
    hashes: {
      controlSha256: crypto.createHash('sha256').update(control).digest('hex'),
    },
    reviewGates: ['Coordinate system validation', 'Emission-unit QA', 'Meteorology approval', 'Receptor-grid approval', 'Building downwash review'],
  };
}

export function parseAermodOutput(text = '') {
  const version = text.match(/AERMOD(?:\s+MODEL)?\s*(?:VERSION|VER\.?)?\s*[:=]?\s*(\d{5})/i)?.[1] || null;
  const fatalErrors = [...text.matchAll(/\*\*\s*FATAL\s+ERROR\s*\*\*\s*([^\r\n]*)/gi)].map(match => match[1].trim());
  const warnings = [...text.matchAll(/\*\*\s*WARNING\s*\*\*\s*([^\r\n]*)/gi)].map(match => match[1].trim());
  const maxima = [...text.matchAll(/(?:MAXIMUM|HIGH)\s+([0-9.E+-]+)\s*(?:MICROGRAMS\/M\*\*3|UG\/M3|µG\/M3)?/gi)]
    .map(match => Number(match[1])).filter(Number.isFinite);
  return {
    modelVersion: version,
    fatalErrors,
    warnings,
    maxima,
    validRun: fatalErrors.length === 0 && !!version,
    outputSha256: crypto.createHash('sha256').update(text).digest('hex'),
    requiresModelerReview: true,
  };
}

export async function runAermodJob({ manifest, files = {} }) {
  const readiness = assessAermodReadiness(manifest);
  if (!readiness.ready) return { status: 'blocked', readiness };

  const executable = path.resolve(process.env.AERMOD_EXECUTABLE);
  if (!fs.existsSync(executable)) throw new Error('Configured AERMOD executable does not exist');
  fs.mkdirSync(JOB_ROOT, { recursive: true });
  const jobId = crypto.randomUUID();
  const jobDir = path.join(JOB_ROOT, jobId);
  fs.mkdirSync(jobDir, { recursive: true });

  for (const [name, base64] of Object.entries(files)) {
    const safeName = path.basename(name);
    const bytes = Buffer.from(base64, 'base64');
    if (bytes.length > 25 * 1024 * 1024) throw new Error(`${safeName} exceeds 25 MB`);
    fs.writeFileSync(path.join(jobDir, safeName), bytes);
  }

  const controlFile = path.basename(manifest.controlFile);
  if (!fs.existsSync(path.join(jobDir, controlFile))) throw new Error('AERMOD control file was not uploaded');
  if (controlFile.toLowerCase() !== 'aermod.inp') {
    fs.copyFileSync(path.join(jobDir, controlFile), path.join(jobDir, 'aermod.inp'));
  }
  const result = await execute(executable, jobDir);
  const outputs = fs.readdirSync(jobDir);
  const primaryOutput = outputs.find(name => /^aermod\.out$/i.test(name)) || outputs.find(name => /\.out$/i.test(name));
  const parsedOutput = primaryOutput ? parseAermodOutput(fs.readFileSync(path.join(jobDir, primaryOutput), 'utf8')) : null;
  return {
    jobId,
    status: result.code === 0 ? 'completed-needs-modeler-review' : 'failed',
    readiness,
    exitCode: result.code,
    stdout: result.stdout.slice(-20_000),
    stderr: result.stderr.slice(-20_000),
    configuredExecutable: executable,
    capturedModelVersion: parsedOutput?.modelVersion || manifest.modelVersion || null,
    parsedOutput,
    outputFiles: fs.readdirSync(jobDir).map(name => ({
      name,
      sha256: crypto.createHash('sha256').update(fs.readFileSync(path.join(jobDir, name))).digest('hex'),
    })),
  };
}

function sanitize(value) {
  return String(value || '').replace(/[\r\n]/g, ' ').trim();
}

function sanitizeId(value) {
  const id = String(value || '').replace(/[^A-Za-z0-9_]/g, '').slice(0, 8);
  if (!id) throw new Error('AERMOD source ID is required');
  return id;
}

function number(value) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`Invalid numeric AERMOD value: ${value}`);
  return parsed;
}

function execute(executable, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn(executable, [], { cwd, windowsHide: true, timeout: 10 * 60 * 1000 });
    let stdout = '';
    let stderr = '';
    child.stdout.on('data', chunk => { stdout += chunk; });
    child.stderr.on('data', chunk => { stderr += chunk; });
    child.on('error', reject);
    child.on('close', code => resolve({ code, stdout, stderr }));
  });
}
